"""empty message

Revision ID: 9384c9ffc64f
Revises: 
Create Date: 2020-03-04 00:38:53.234865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9384c9ffc64f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cname', sa.String(length=50), nullable=False),
    sa.Column('article_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('sessions',
    sa.Column('sessionid', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('sessionid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('head_portrait', sa.String(length=300), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('is_forbidden', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('article',
    sa.Column('aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aname', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=10000), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['category.cid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('comments',
    sa.Column('comid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('comment_time', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('comid')
    )
    op.create_table('tag',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tname', sa.String(length=50), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['article.aid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('comments')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('sessions')
    op.drop_table('category')
    # ### end Alembic commands ###
